# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import decimal
from typing import Optional

import my.module


@dataclasses.dataclass()
class Job:
    id: int
    status: my.module.JobStatus
    priority: Optional[decimal.Decimal]
