# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import AsyncIterator, Iterator, Optional

import my.module
import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


GET_JOB = """-- name: get_job \\:one
SELECT id, status, priority FROM jobs
WHERE id = :p1 LIMIT 1
"""


LIST_JOBS_BY_STATUS = """-- name: list_jobs_by_status \\:many
SELECT id, status, priority FROM jobs
WHERE status = :p1
ORDER BY priority
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_job(self, *, id: int) -> Optional[models.Job]:
        row = self._conn.execute(sqlalchemy.text(GET_JOB), {"p1": id}).first()
        if row is None:
            return None
        return models.Job(
            id=row[0],
            status=row[1],
            priority=row[2],
        )

    def list_jobs_by_status(self, *, status: my.module.JobStatus) -> Iterator[models.Job]:
        result = self._conn.execute(sqlalchemy.text(LIST_JOBS_BY_STATUS), {"p1": status})
        for row in result:
            yield models.Job(
                id=row[0],
                status=row[1],
                priority=row[2],
            )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_job(self, *, id: int) -> Optional[models.Job]:
        row = (await self._conn.execute(sqlalchemy.text(GET_JOB), {"p1": id})).first()
        if row is None:
            return None
        return models.Job(
            id=row[0],
            status=row[1],
            priority=row[2],
        )

    async def list_jobs_by_status(self, *, status: my.module.JobStatus) -> AsyncIterator[models.Job]:
        rows = (await self._conn.execute(sqlalchemy.text(LIST_JOBS_BY_STATUS), {"p1": status})).all()
        for row in rows:
            yield models.Job(
                id=row[0],
                status=row[1],
                priority=row[2],
            )
